import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const styles = {
  button: {
    borderRadius: "6px",
    backgroundColor: "grey",
    color: "#fff",
    padding: "12px",
    fontSize: "22px",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex", gap: "10px" }}>
          <Link href="/csr" style={styles.button}>
            CSR
          </Link>
          <Link href="/ssr" style={styles.button}>
            SSR
          </Link>
          <Link href="/ssg" style={styles.button}>
            SSG
          </Link>
          <Link href="/isr" style={styles.button}>
            ISR
          </Link>
          <Link href="/ssr+csr" style={styles.button}>
            SSR + CSR
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
